version: '3.4'

services:
  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: govwifi_test
    ports:
      - "13306:3306"

  app:
    build: .
    environment:
      DB_NAME: govwifi_test
      DB_PASS: root
      DB_USER: root
      DB_HOSTNAME: db
      RACK_ENV: development
      AUTHORISED_EMAIL_DOMAINS_REGEX: "\\.gov\\.uk$$"
    ports:
        - "8080:8080"
    depends_on:
      - db
